services:
  - type: web
    name: get-reech-laravel
    env: docker
    repo: https://github.com/Gatdor/GET-REECH
    rootDir: backend
    buildCommand: composer install --no-dev --optimize-autoloader && npm ci && npm run production && php artisan migrate --force
    startCommand: php-fpm -D && nginx -g "daemon off;"